export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 569094,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    popularity: 4485.474,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 7.5,
    vote_count: 3063,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
    id: 667538,
    title: "Transformers: Rise of the Beasts",
    original_language: "en",
    original_title: "Transformers: Rise of the Beasts",
    overview:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 2560.837,
    release_date: "2023-06-06",
    video: false,
    vote_average: 7.5,
    vote_count: 2644,
  },
  {
    adult: false,
    backdrop_path: "/zgngWYj9kydOTP3bE1MZIi1YIq4.jpg",
    id: 3412,
    title: "Return from Death: Frankenstein 2000",
    original_language: "en",
    original_title: "Ritorno dalla morte",
    overview:
      "When a woman is beaten into a coma and saved from being raped by her handyman (Donald O'Brien), the local security force does a cover-up to save the town's reputation and frames the saviour. After he hangs himself, the woman's strange comatose psi-powers revive him from the dead to exact revenge.",
    poster_path: "/6zZKpFuzfO8ELyovhlHpVPNxQgK.jpg",
    media_type: "movie",
    genre_ids: [27],
    popularity: 3.051,
    release_date: "1991-01-01",
    video: false,
    vote_average: 4.917,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/tawuH0BCCAKPQozljGmccBc09H5.jpg",
    id: 2314,
    title: "The Long Run",
    original_language: "en",
    original_title: "The Long Run",
    overview:
      "A failed track coach finally finds someone who he believes has what it takes to win. The Comrades Marathon is a 90-k race in South Africa. An aging running coach, Barry, wants to field a winner; he's working with four men from a factory, but when he's fired to make way for a smooth, corporate type, he's at loose ends. Then he sees Christine, a Namibian immigrant who runs to forget her troubles. He offers to coach her and soon she's living at his house, following his diet and training regimen. But his single-mindedness gets to her: she wants a job and a place of her own. Plus, the man who replaced Barry likes her and wants her away from Barry. Can runner and coach (woman and man, African and European) sort out their complex relationship before the race? Written by",
    poster_path: "/Su00JYfQ4Nfa3BsrRZ8YGF2Emo.jpg",
    media_type: "movie",
    genre_ids: [18],
    popularity: 1.964,
    release_date: "2001-05-04",
    video: false,
    vote_average: 6.25,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: "/wRxLAw4l17LqiFcPLkobriPTZAw.jpg",
    id: 697843,
    title: "Extraction 2",
    original_language: "en",
    original_title: "Extraction 2",
    overview:
      "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
    poster_path: "/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
    media_type: "movie",
    genre_ids: [28, 53],
    popularity: 424.974,
    release_date: "2023-06-09",
    video: false,
    vote_average: 7.54,
    vote_count: 1605,
  },
  {
    adult: false,
    backdrop_path: "/oqP1qEZccq5AD9TVTIaO6IGUj7o.jpg",
    id: 455476,
    title: "Knights of the Zodiac",
    original_language: "en",
    original_title: "Knights of the Zodiac",
    overview:
      "When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?",
    poster_path: "/qW4crfED8mpNDadSmMdi7ZDzhXF.jpg",
    media_type: "movie",
    genre_ids: [14, 28, 12],
    popularity: 656.192,
    release_date: "2023-04-27",
    video: false,
    vote_average: 6.695,
    vote_count: 724,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    id: 385687,
    title: "Fast X",
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    media_type: "movie",
    genre_ids: [28, 80, 53],
    popularity: 1363.383,
    release_date: "2023-05-17",
    video: false,
    vote_average: 7.315,
    vote_count: 3287,
  },
  {
    adult: false,
    backdrop_path: "/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg",
    id: 603692,
    title: "John Wick: Chapter 4",
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    media_type: "movie",
    genre_ids: [28, 53, 80],
    popularity: 808.917,
    release_date: "2023-03-22",
    video: false,
    vote_average: 7.826,
    vote_count: 4126,
  },
  {
    adult: false,
    backdrop_path: "/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg",
    id: 976573,
    title: "Elemental",
    original_language: "en",
    original_title: "Elemental",
    overview:
      "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
    poster_path: "/8riWcADI1ekEiBguVB9vkilhiQm.jpg",
    media_type: "movie",
    genre_ids: [16, 35, 10751, 14, 10749],
    popularity: 742.53,
    release_date: "2023-06-14",
    video: false,
    vote_average: 7.613,
    vote_count: 769,
  },
  {
    adult: false,
    backdrop_path: "/uFKlV3ZAFkuY37RFhKfqEew8kzt.jpg",
    id: 1076487,
    title: "Warhorse One",
    original_language: "en",
    original_title: "Warhorse One",
    overview:
      "A gunned down Navy SEAL Master Chief must guide a child to safety through a gauntlet of hostile Taliban insurgents and survive the brutal Afghanistan wilderness.",
    poster_path: "/jP2ik17jvKiV5sGEknMFbZv7WAe.jpg",
    media_type: "movie",
    genre_ids: [28, 18, 10752],
    popularity: 731.233,
    release_date: "2023-06-30",
    video: false,
    vote_average: 7.234,
    vote_count: 154,
  },
];
